jenkinsdata:
  image: bskjerven/jenkins-data
  environment:
    - TZ=Australia/Perth
  container_name: jenkins-data

jenkinsmaster:
  image: bskjerven/jenkins-master
  environment:
    - TZ=Australia/Perth
  volumes_from:
    - jenkinsdata
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  ports:
    - "50000:50000"
  container_name: jenkins-master

jenkinsnginx:
  image: bskjerven/jenkins-nginx
  environment:
    - TZ=Australia/Perth
  ports:
    - "80:80"
  links:
    - jenkinsmaster:jenkins-master
  container_name: jenkins-nginx
